### ISSUE TITLE
huge memory consumption in a test

### ISSUE THREAD

**Issue by claireroche** [LIHPC-Computational-Geometry/gmds#209]
The test AeroPipelineTestClass.AeroPipeline2D_User_DA :
https://github.com/LIHPC-Computational-Geometry/gmds/blob/repair_aero_183/claire/tst/AeroPipelineTestSuite.h#L132

seems to take a lot of memory; we should investigate.
When the method MeshAlignement
https://github.com/LIHPC-Computational-Geometry/gmds/blob/repair_aero_183/claire/src/AeroPipeline_2D.cpp#L413

is called.

A file .vtk sent by mail to the project member is needed to execute the test.

**Comment by nicolaslg** [comment]
- confirmed memory leak in Fastlocalize;
 - Fastlocalize, or rather its research tree for fast queries, can be created once in  `AeroPipeline_2D::MeshAlignement` instead of multiple times in the loop.
