### ISSUE TITLE
Warning on conversion type from 'gmds::TCellID' to signed type 'int'

### ISSUE THREAD

**Issue by claireroche** [LIHPC-Computational-Geometry/gmds#220]
I have a warning in CLion when using a variable assignment. This warning is:
"Clang-Tidy: Narrowing conversion from 'gmds::TCellID' (aka 'unsigned int') to signed type 'int' is implementation-defined"
 
For instance, with the code:
`Variable<double> *m_distance;`
`double b = m_distance->value(n.id());`
Where n is a Node. n.id() is a gmds::TCellID (aka "unsigned int'), but in the class **Variable.h**, for the method **value**, here is the method signature:
`T& value(const int &i) { return m_data[i]; }`

(You can find an example on the file **AdvectedPointRK4_3D.cpp**, at line 254, 255, ...)

Shouldn't the "const int &i" be a "const TCellID &i" ?

**Comment by franck-ledoux** [comment]
done
