### ISSUE TITLE
MeshDoctor : buildE() on a 3D mesh model with R and R2N but which has only F created

### ISSUE THREAD

**Issue by claireroche** [LIHPC-Computational-Geometry/gmds#260]
I create a mesh, with the complete 3D mesh model 
`gmds::MeshModel(DIM3 | R | F | E | N | R2N | F2N | E2N | R2F | F2R | F2E | E2F | R2E | E2R | N2R | N2F | N2E)`
and I initialize it with a surface mesh. After this step, my mesh contains nodes F, faces F, and F2N.
Now, I want to build the Edges and connectivities, so I call the method
`gmds::MeshDoctor doc(&m);
doc.buildE();`
But it does not create any edge.

In fact, in the method `buildE()`, there is this condition branch:
`if(mod.has(R) && mod.has(R2N)){...}
else if(mod.has(F) && mod.has(F2N)){...}
else
    throw GMDSException("MeshDoctor::buildE Not yet implemented");`

As there are R and R2N in my model, but there is no region created at this moment, then the Edges are not built.

First, I am in a very specific case. As I am working on an advancing front algorithm, my mesh is just initialized here with a surface mesh, and will create regions after this step, so I can hardly change the model of the mesh.

I was thinking to several possibilities:
1. I can create a true surface mesh, with only faces (not regions), read my surface mesh, create the edges and connectivities with the MeshDoctor, initialized all my quantities on this mesh (geometric classification, variables, etc), then copy all these information into a new mesh with a model with Regions.
2. I was wondering if it is possible to change the second condition to just `if` instead of `else if` ? But maybe it will be time consuming for 3D meshes with R and F.
3. Is it possible to have a method in the MeshDoctor which specifies for example to build the edges from the faces precisely ? (ex: `buildEfromF()`)

Maybe another solution already exist or is more suitable, this is why I present this issue.

A minimal test example `buildE` highlighting my problem is in the `MeshDoctorTestSuite.h` file.

**Comment by nicolaslg** [comment]
I am all for additional `buildEFromF` and `buildEFromR` methods, that the current `buildE` would call.

@franck-ledoux , your thoughts on that one ?

**Comment by franck-ledoux** [comment]
The main issue is to try to build edges in a 3D mesh with regions (R) and trying to build them only from faces.  I think we reach the limit of providing generic functionalities (building edges here). We can add "buildEFromF". It must just be specified that several connectivities will not be created (to regions if they are in the model and really exist).
