### ISSUE TITLE
fix the bypass for the install_tree with spack 0.20.0

### ISSUE THREAD

**Issue by nicolaslg** [LIHPC-Computational-Geometry/gmds#282]
The bypass we used to force the installation of the dependencies using spack to avoid the plateform/compiler/hash no longer works with the latest release 0.20.0.

Relates to https://github.com/LIHPC-Computational-Geometry/gmds/pull/281

**Comment by franck-ledoux** [comment]
It still world (see branch issue-266) but the syntax has changed.

**Comment by nicolaslg** [comment]
The CI is now based on spack-0.20.1, no need to maintain the previous install_tree substitution sed command.
