### ISSUE TITLE
Element Quality: Skew

### ISSUE THREAD

**Issue by claireroche** [LIHPC-Computational-Geometry/gmds#388]
1. I think the skew quality over hexahedral element is not computed accurately.

In quality/src/HexQuality.cpp file:
https://github.com/LIHPC-Computational-Geometry/gmds/blob/main/quality/src/HexQuality.cpp
The `skew()` is not computed on normalized principal axes X1, X2, and X3 as it should according to Sandi'as report on Verdict geometric quality library (https://www.osti.gov/servlets/purl/901967).
I don't know if it is wanted or not. In the current state, the skewness of an element is not necessary between 0 and 1.

2. It Could be useful to add skew computation on quads too, in the `QuadQuality` class, as described in Sandia's Verdict library.

**Comment by claireroche** [comment]
Example to add in `HexEvalTestSuite.h`:
(https://github.com/LIHPC-Computational-Geometry/gmds/blob/main/quality/tst/HexEvalTestSuite.h)

`HexQuality hq = HexQuality::build(math::Point(188,28,29),
	                                     math::Point(191,28,29),
	                                     math::Point(191,31,26),
	                                     math::Point(188,31,26),
	                                     math::Point(188,27,28),
	                                     math::Point(191,27,28),
	                                     math::Point(191,29,25),
	                                     math::Point(188,29,25));
	   std::cout << "Skew: " << hq.skew() << std::endl;`

The returned value is 12, while the hexahedron is shaped as illustrated below.

[ROCHE_TIKZ.pdf](https://github.com/user-attachments/files/16029724/ROCHE_TIKZ.pdf)

**Comment by nicolaslg** [comment]
Thanks for the report !

- I concur that the implementation is faulty
- we should add the skew for the quads
