### ISSUE TITLE
the standalone build fails (GLPK_LIB is set to NOT_DEFINED)

### ISSUE THREAD

**Issue by nicolaslg** [LIHPC-Computational-Geometry/gmds#74]
When not using an externally installed glpk library (GLPK_LIB andGLPK_INC not set, cmake called with no options), glpk is indeed built but the GLPK_LIB path is set to  NOT_DEFINED, making the glpk target not usable :
`No rule to make target 'NOT_DEFINED/libglpk.a', needed by 'singGraphBuild/singGraphBuilder'.  Stop.`

Tested on linux.

**Comment by Daniel-Dht** [comment]
GLPK_LIB and GLPK_INC are now set and forced into cmake cache with correct values when at least one of them is not user defined.

- On linux, glpk build will depend on the cmake variable BUILD_SHARED_LIBS. Windows builds will still only use glpk dll for now.
- CMake install commands for glpk exist now on linux
