### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by lelandaisb** [LIHPC-Computational-Geometry/gmds#93]
I try to use GMDS on my own code. I have installed GMDS in $HOME/gmds/install.
My project use cmake. My CMakeLists.txt looks like this:

     set(gmds_ROOT $ENV{HOME}/gmds/install)
     ...
     find_package(gmds REQUIRED)

The cmake command returns an error due to a missing file:

     CMake Error at $HOME/gmds/install/lib/gmds/cmake/gmdsConfig.cmake:33 (include):
       include could not find requested file:

       $HOME/gmds/install/lib/gmds/cmake/../gmds.cmake

     Call Stack (most recent call first):
       CMakeLists.txt:16 (find_package)

**Comment by HexMsh** [comment]
I will check that by tomorrow I hope
